# this script takes all the resfiles generated by change_resfile_ptmutant.py and runs backrub
# shell command: /Users/anum/Desktop/ROSETTA/main/source/bin/backrub.macosclangrelease -database /Users/anum/Desktop/ROSETTA/main/database/  -s XXX.pdb -ignore_unrecognized_res -ex1 -ex2 -extrachi_cutoff 0 -backrub:ntrials 1000 -resfile resYYY.res

import sys, os
import shutil

from subprocess import call
import shlex

chainletter_list = ["A", "B", "C", "D", "E"]

numchains = input("How many chains does your structure have? ")
for j in range(numchains):

    chainletter = chainletter_list[j]
    numres = input("How many residues does chain " + chainletter + " of your structure have? " )

    chainfolder = "chain" + chainletter
    os.makedirs(chainfolder)

    for i in range(numres):
        resfile = "res" + str(i+1) + ".res"
        resfolder = "res" + str(i+1)
        path = chainfolder + "/" + resfolder
        os.makedirs(path)
        
        shellstring = "/Users/anum/Desktop/ROSETTA/main/source/bin/backrub.macosclangrelease -database /Users/anum/Desktop/ROSETTA/main/database/  -s 7msf_noH2O_noRNA.pdb -ignore_unrecognized_res -ex1 -ex2 -extrachi_cutoff 0 -backrub:ntrials 1000 -resfile " + chainletter + "_" + resfile

        call(shlex.split(shellstring))
        shutil.move("/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/7msf_noH2O_noRNA_0001.pdb", "/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/" + "/" + chainfolder + "/" +resfolder + "/" + "7msf_noH2O_noRNA_0001.pdb")
        shutil.move("/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/7msf_noH2O_noRNA_0001_low.pdb", "/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/"  + "/" + chainfolder + "/" + resfolder + "/" + "7msf_noH2O_noRNA_0001_low.pdb")
        shutil.move("/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/7msf_noH2O_noRNA_0001_last.pdb", "/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/" +  "/" + chainfolder + "/" + resfolder + "/" + "7msf_noH2O_noRNA_0001_last.pdb")
        shutil.move("/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/score.sc", "/Users/anum/Dropbox/Research/Structures/MS2/backrub/trial4_ptmut_assembly/"  + "/" + chainfolder + "/" + resfolder + "/" + "score.sc")