# this script takes all the resfiles generated by change_resfile_ptmutant.py and runs backrub
# shell command: /Users/anum/Desktop/ROSETTA/main/source/bin/backrub.macosclangrelease -database /Users/anum/Desktop/ROSETTA/main/database/  -s XXX.pdb -ignore_unrecognized_res -ex1 -ex2 -extrachi_cutoff 0 -backrub:ntrials 1000 -resfile resYYY.res

import sys, os

# pdbname = input("What is your .pdb file called? Include .pdb. ")

# for i in range(129):
from subprocess import call
import shlex

numres = input("How many residues does your structure have?" )

for i in range(numres):
    resfile = "res" + str(i+1) + ".res"
    shellstring = "/Users/anum/Desktop/ROSETTA/main/source/bin/backrub.macosclangrelease -database /Users/anum/Desktop/ROSETTA/main/database/  -s 7msf_monomer.pdb -ignore_unrecognized_res -ex1 -ex2 -extrachi_cutoff 0 -backrub:ntrials 1000 -resfile " + resfile

    call(shlex.split(shellstring))